env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  consistent-return: off
  default-case: off
  max-len: off
  no-plusplus: off
  no-restricted-syntax: off
  import/no-unresolved: off
  import/extensions: off
  no-await-in-loop: off
  no-loop-func: off
  no-bitwise: off
  no-mixed-operators: off
  no-continue: off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  no-console: off
